### ISSUE TITLE
The Donate bar won't go away

### ISSUE THREAD

**Issue by tomaxxx** [mobnetic/BitcoinChecker#102]
Hi,
I've donate a while ago, then mistakenly deleted the app from my phone. After reinstalling it, the donate  bar won't go away. I tried to donate $1 to get rid of it, but it I can't, as I am considered a registered owner on the store.
Any idea ?
Best regards.

**Comment by MaciejCiemiega** [comment]
Donations via Google Play Store are disabled now anyway. Donations in crypto-currencies are not tracked so they cannot be restored.
