### ISSUE TITLE
Add exchange: FoxBit

### ISSUE THREAD

**Issue by schiavonxv** [mobnetic/BitcoinChecker#142]
Can you add FoxBit.com.br in your app?

API: https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC

Thank you ;)

**Comment by MaciejCiemiega** [comment]
Hello, I've just added this exchange into BitcoinChecker. You should see new version (1.5.3) available on Google Play Store within few hours.
Cheers!
