### ISSUE TITLE
Bitstamp price not updating

### ISSUE THREAD

**Issue by marshallhayner** [mobnetic/BitcoinChecker#143]
Bitstamp BTC/USD price on BitcoinChecker does not seem to be updating... Stuck at $319.11 while the actual current price is $282.71

**Comment by MaciejCiemiega** [comment]
I've just tested it and it works properly. Price matches the price from their API: https://www.bitstamp.net/api/ticker/
Can you please provide some more details? Is there any error or the price is downloaded normally?

**Comment by schossel** [comment]
It isn't working for me, too. It says "Error: cannot connect to server".

**Comment by MaciejCiemiega** [comment]
Yeah, now it isn't working, see their API:
https://www.bitstamp.net/api/ticker/
You can see on their website that they have some issues that they need to resolve:
https://www.bitstamp.net/

**Comment by schossel** [comment]
I just read about the Bitstamp Hack and that they suspended their trading. So no fault on Bitcoin Checkers part.
