### ISSUE TITLE
please add quadrigacx

### ISSUE THREAD

**Issue by mr-e-** [mobnetic/BitcoinChecker#149]
Now that both cavirtex and vault of satoshi have shut down in Canada,  quadriga is the new leader.

**Comment by NatasataN** [comment]
Yeah, quadrigacx.com is my main place.  I noticed it's included in the source of the module. Hopefully we get it in the next update.

**Comment by MaciejCiemiega** [comment]
Hi,
as noticed by NatasataN: QuadrigaCX is already implemented, but not released yet.
When I'll find some time I will release new 1.5.4 update (with this quadrigacx) soon :)
Cheers!

**Comment by mr-e-** [comment]
Thanks. Maybe CoinTrader as well?

**Comment by MaciejCiemiega** [comment]
I've created separate issue for that: https://github.com/mobnetic/BitcoinChecker/issues/150

**Comment by MaciejCiemiega** [comment]
Update 1.5.4 with this exchange was just released on Google Play Store. It should take few hours since it will be visible to all users.
Cheers!

**Comment by NatasataN** [comment]
Thanks alot! That's great app support man! I will be donating for sure :)

**Comment by MaciejCiemiega** [comment]
Already implemented in version 1.5.4.
