### ISSUE TITLE
Add support for CoinTrader exchange

### ISSUE THREAD

**Issue by MaciejCiemiega** [mobnetic/BitcoinChecker#150]
API: https://www.cointrader.net/api4/stats/daily/BTCUSD
Pairs: BTCUSD and BTCCAD

**Comment by MaciejCiemiega** [comment]
Update 1.5.4 with this exchange was just released on Google Play Store. It should take few hours since it will be visible to all users.
Cheers!

**Comment by mr-e-** [comment]
Awesome thanks!!
