### ISSUE TITLE
bter exchange info not syncing?

### ISSUE THREAD

**Issue by keymaster312** [mobnetic/BitcoinChecker#152]
Noticed on two devices, no data since 2/15?

**Comment by mhiller** [comment]
Bter was hacked and promptly taken offline on 2/15 
http://www.coindesk.com/bter-bitcoin-stolen-cold-wallet-hack/

Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by so142001** [comment]
Bter will be up again soon.
