### ISSUE TITLE
add exchange: bit-x.com and hashnest.com

### ISSUE THREAD

**Issue by marec2000** [mobnetic/BitcoinChecker#158]
Both are major trading places for mining shares. Public API is available, documentation can be found [here](https://bit-x.com/guide/api) for bit-x and [here](https://www.hashnest.com/hashnest_api) for hashnest.

**Comment by MaciejCiemiega** [comment]
1. bit-x.com doesn't have any kind of API to fetch the set of currency pairs to trade. It has however only a ticker API but it may be not enough if they do change their currency pairs in time. If the set of pairs is stable (can you confirm that?) I can hardcode them inside app but this is the worse way. If you can tell that set of pairs is stable please prepare a list of all of them and I would see what can be done here.
2. It seems that hashnest doesn't have any public API at all, so there is no possibility to add this exchange. If you will (in future) find out that they start to provide some public API please let me know.

Greetings.

**Comment by marec2000** [comment]
1. The set of trading pairs has been stable over at least half a year now. Available pairs are listed in the api documentation (= BTCUSD, BTCEUR, BTCGBP, LTCUSD, LTCBTC, LTCEUR, LTCGBP, GHSBTC, GHSLTC, GHSUSD, GHSEUR, GHSGBP, EURUSD, EURGBP, GBPUSD).
2. Yes, seems private API only. Haven't noticed that before.

Anyway, would be good if you can do the trick for (1).

Thanks in advance.

**Comment by MaciejCiemiega** [comment]
Haha, they pairs are specified indeed. I was busy looking for any kind of API to return set of pairs and I totally missed them, thanks!:)

**Comment by MaciejCiemiega** [comment]
I've added support for this exchange and will include it in next update of Bitcoin Checker (in week or two).
Cheers!

**Comment by MaciejCiemiega** [comment]
bit-x.com is included in 1.5.9 update that was just uploaded to Google Play Store. It should be visible to all users within few hours. Cheers!

**Comment by marec2000** [comment]
Just have updated to 1.5.9 - works like expected. Good job! Thanks.
