### ISSUE TITLE
Non-existing pairs on btc-e

### ISSUE THREAD

**Issue by avirdoz** [mobnetic/BitcoinChecker#161]
xrp, ftc and trc was permanently removed from btc-e.

**Comment by MaciejCiemiega** [comment]
Hello, thanks for reporting this. I will surely remove these pairs, but there is a need to migrate to API v3 anyway. It will bring dynamic currency syncing so the list of pairs could be updated from within the app.

Currency pairs:
https://btc-e.com/api/3/info

Ticker:
https://btc-e.com/api/3/ticker/btc_usd

**Comment by MaciejCiemiega** [comment]
Support for dynamic currency pairs for btc-e is included in 1.5.9 update that was just uploaded to Google Play Store. It should be visible to all users within few hours. Cheers!
