### ISSUE TITLE
Please someone, bring back cavirtex.

### ISSUE THREAD

**Issue by Transisto** [mobnetic/BitcoinChecker#163]
The exchange came back months ago.

Thank You

**Comment by MaciejCiemiega** [comment]
Hello, can you please elaborate a bit about the issue? I'm a bit confused because this exchange is supported by Bitcoin Checker and it works as it should.

**Comment by Transisto** [comment]
The name is cavirtex not virtex ,  CAnadian VIRTual EXchange...   there is
an even exchange called virtex.com

**Comment by MaciejCiemiega** [comment]
Thanks for explanation.
You could just simply say to "change name of the exchange", not to "bring it back" because it was never removed.
I've renamed this exchange in 1.5.9 update so no you would see "CaVirtEx" name. Cheers!

**Comment by Transisto** [comment]
Well I just could not see it and thought it was not there,  thanks
