### ISSUE TITLE
New Exchange : BtcxIndia

### ISSUE THREAD

**Issue by Ashesh3** [mobnetic/BitcoinChecker#164]
Please add this api https://btcxindia.com/api/ 

Ticker: https://btcxindia.com/api/ticker

**Comment by MaciejCiemiega** [comment]
Hello, I will try to add support for this exchange in next release.
Cheers!

**Comment by MaciejCiemiega** [comment]
Thanks, I've added this exchange in 1.5.10 update, it should be available on Google Play Store within few hours.
Cheers!
