### ISSUE TITLE
"Parsing Error" for Kraken BTC Prices

### ISSUE THREAD

**Issue by gordonsross** [mobnetic/BitcoinChecker#166]
"Parsing Error" is being displayed for Kraken BTC/currency cross prices.

**Comment by arkaitzj** [comment]
Right, seeing the issue for BTC/Euro pairs, LTC/Euro and ETH/Euro working ok

**Comment by cjlewis999** [comment]
Also for btc/gbp

**Comment by MaciejCiemiega** [comment]
Thanks for reporting that. I've just checked it and it seem that they have something really weird going on in their API.
There are BTC pairs duplicated, but with ".d" addition. Does anyone know whether it means anything, or is it some kind of issue with their API??
```
For example:
"XXBTZEUR":{"altname":"XBTEUR","aclass_base":"currency","base":"XXBT","aclass_quote":"currency","quote":"ZEUR","lot":"unit","pair_decimals":5,"lot_decimals":8,"lot_multiplier":1,"leverage_buy":[1.5,2,2.5,3,5],"leverage_sell":[1.5,2,2.5,3,5],"fees":[[0,0.26],[10000,0.24],[50000,0.22],[100000,0.2],[250000,0.18],[500000,0.16],[1000000,0.14],[5000000,0.12],[10000000,0.1]],"fees_maker":[[0,0.16],[10000,0.14],[50000,0.12],[100000,0.1],[250000,0.08],[500000,0.06],[1000000,0.04],[5000000,0.02],[10000000,0]],"fee_volume_currency":"ZUSD","margin_call":80,"margin_stop":40},
"XXBTZEUR.d":{"altname":"XBTEUR.d","aclass_base":"currency","base":"XXBT","aclass_quote":"currency","quote":"ZEUR","lot":"unit","pair_decimals":5,"lot_decimals":8,"lot_multiplier":1,"leverage_buy":[],"leverage_sell":[],"fees":[[0,0.36],[10000,0.34],[50000,0.32],[100000,0.3],[250000,0.28],[500000,0.26],[1000000,0.24],[5000000,0.22],[10000000,0.2]],"fee_volume_currency":"ZUSD","margin_call":80,"margin_stop":40}
```

**Comment by gordonsross** [comment]
Looks like the '.d' extension relates to their 'Dark Pool' trade pairs. 

http://trusck.com/all/bitcoin-weekly-2015-june-17-gyft-blockchain-gift-cards-coinbase-instant-exchange-kraken-dark-pool-trading-and-more/

**Comment by MaciejCiemiega** [comment]
Ok... I will have to ignore them for now, because I cannot do anything with them (like read ticker)
https://api.kraken.com/0/public/Ticker?pair=XXBTZEUR.d

**Comment by gordonsross** [comment]
I don't think that too many people will be bothered by those pairs being ignored.

**Comment by gordonsross** [comment]
And many thanks for looking at it, by the way.

**Comment by MaciejCiemiega** [comment]
Thanks, I've included a fix for that in 1.5.10 update, it should be available on Google Play Store within few hours. Please re-synchronize currency pairs on Kraken after the update - it should fetch 21 instead of 26 pairs.
Cheers!

**Comment by gordonsross** [comment]
Thank you.

**Comment by gordonsross** [comment]
1.5.10 looks to be working fine. And to confirm, 21 pairs instead of 26.
Thanks again.

**Comment by cjlewis999** [comment]
Thank you. I can also confirm it's working after resynchronisation.
