### ISSUE TITLE
Error when trying to download the currency pairs of Cryptsy.

### ISSUE THREAD

**Issue by acaciosc** [mobnetic/BitcoinChecker#167]
Last sync: never
Both "Error: Unknown error" and "Error: Cannot connect to server" are shown when trying to download the currency pairs of Cryptsy.

**Comment by MaciejCiemiega** [comment]
Hello, it means that there is no connectivity with exchange server - and that is not fault of Bitcoin Checker app.

After testing their API it looks like they have some problems with their API.

Bitcoin Checker uses:
http://pubapi.cryptsy.com/api.php?method=orderdatav2
to access currency pairs, which redirects to following urls, regarding of region:
http://pubapi1.cryptsy.com/api.php?method=orderdatav2
http://pubapi2.cryptsy.com/api.php?method=orderdatav2
(more info in their documentation: https://www.cryptsy.com/pages/publicapi).
You can see that only pubapi2 works, and trying to access pubapi1 results in "502 Bad Gateway" error.

Greetings.
