### ISSUE TITLE
Request to add shapeshifter (largest api!)

### ISSUE THREAD

**Issue by Ashesh3** [mobnetic/BitcoinChecker#180]
Main endpoint : https://shapeshift.io/rate/

Specific pair : https://shapeshift.io/rate/<pair>

Example:
https://shapeshift.io/rate/btc_doge
https://shapeshift.io/rate/btc_ltc

Thanks, its a great api!

**Comment by MaciejCiemiega** [comment]
Hi,
This exchange will be available in update 1.6, which I will try to release today.

Greetings.

**Comment by Ashesh3** [comment]
Thanks :)
