### ISSUE TITLE
[Feature Request] Add INR exchange Coinsecure

### ISSUE THREAD

**Issue by vivek0** [mobnetic/BitcoinChecker#187]
API https://api.coinsecure.in

**Comment by vivek0** [comment]
Hey @MaciejCiemiega a little help here?

This URL gives ticker data in JSON format https://api.coinsecure.in/v0/noauth/ticker

**Comment by MaciejCiemiega** [comment]
This exchange was included in 1.6.1 update of Bitcoin Checker and should be available within few hours on Google Play Store.

**Comment by vivek0** [comment]
Thanks! It's been update on Playstore now :smile:

**Comment by vivek0** [comment]
@MaciejCiemiega API update V1  https://api.coinsecure.in/v1/exchange/ticker
