### ISSUE TITLE
[Feature Request] Make pull-down notification optional.

### ISSUE THREAD

**Issue by dr3amr2** [mobnetic/BitcoinChecker#189]
I have a lot of coins added to the list and it clutters up the pull-down notification.  Can we make the pull-down notification an optional setting?

**Comment by MaciejCiemiega** [comment]
It is optional and it can be configured to every Checker independently.
When adding/editing a Checker there is a checkbox called "Show notification", just uncheck it if you don't want to have a notification occupying your notification area.

Please let me know if that helped.
Greetings.
