### ISSUE TITLE
We wait for application updates.

### ISSUE THREAD

**Issue by Arthur4** [mobnetic/BitcoinChecker#198]
Thank you..
Updated Huobi urls, fixes #190.
But...
Why is not the Google Play Store app updated?
We wait for application updates.
Quick update, please. ....

**Comment by MaciejCiemiega** [comment]
Hello, nice to hear that you are awaiting the update of Bitcoin Checker:)
The only reason why I haven't published an update was lack of time from my side. But today I've managed to shift my other activities and release an update 1.6.1 so please expect it to be visible on Google Play store within few hours.

**Comment by Arthur4** [comment]
Thank you very much ^^;
