### ISSUE TITLE
ability to change notification area font colors

### ISSUE THREAD

**Issue by yerb** [mobnetic/BitcoinChecker#215]
I am using MIUI dark thame notification area pulldown is too dark for black color font-

**Comment by PingForward** [comment]
The same issue MIUI 7

![screenshot_2016-02-26-12-48-02_com miui home](https://cloud.githubusercontent.com/assets/17492722/13348919/64c53afa-dc87-11e5-9071-8a30b3e6ac24.png)

**Comment by MaciejCiemiega** [comment]
I use @android:style/TextAppearance.Material.Notification.Title and @android:style/TextAppearance.Material.Notification.Line2 for notification text color so I guess they do not override those values to match the style of custom navigation drawer.

@yerb: You've mentioned "MIUI dark thame" so this is not a default theme for MIUI? (I'm completely not familiar with this system).

@yerb, @PingForward As I'm not able to test this I've uploaded new alpha build on Google Play store. You can mark yourself as alpha testers and try new build here: https://play.google.com/apps/testing/com.mobnetic.coinguardian

Please tell (or show) me how it will look now. Also please give me some insight how it looks on "light" theme - it's very important to me whether it adapts to themes or how they solved this in their system.

**Comment by PingForward** [comment]
@MaciejCiemiega sorry man but alpha has this issue too. I changed a few themes and the same black text color. It seems the MIUI always used dark theme.

**Comment by MaciejCiemiega** [comment]
@PingForward then I cannot do anything with it. In this alpha build I've used `?android:attr/textColorPrimaryInverse` and `?android:attr/textColorSecondaryInverse` which are supposed to take colors from theme so it would be adjusted, but I guess they don't support it either.
I have no choice than adding a toggle: go to Settings -> Customize notifications and un-check "Custom notification layout"

![screenshot_20160229-212104](https://cloud.githubusercontent.com/assets/6815900/13407911/23424392-df2b-11e5-9e54-c7d517187f9c.png)

It will replace the current custom layout in notifications (made to be able to put the refresh button on the right) with standard notification layout created by system (so it will be in proper color). You can still use refresh action from expanded notification.

![notification_custom_layout](https://cloud.githubusercontent.com/assets/6815900/13407936/49f3d0aa-df2b-11e5-9d7a-e4b7dd3005d5.png)

**Comment by MaciejCiemiega** [comment]
@PingForward @yerb Have you tried the solution from newest alpha build described in my previous post?

**Comment by PingForward** [comment]
@MaciejCiemiega yes, it's work perfect.

**Comment by MaciejCiemiega** [comment]
Great, I've just released update 1.6.2 to public.
