### ISSUE TITLE
Livecoin some coins price is 0

### ISSUE THREAD

**Issue by goranapo** [mobnetic/BitcoinChecker#255]
Livecoin exchange for some coins price shows as 0. It was good 3 days ago.

**Comment by MaciejCiemiega** [comment]
Can you point some examples? Are you sure that wasn't just a problem with the exchange itself?

**Comment by goranapo** [comment]
I dont see the issue any more, maybe it was the exchange.

**Comment by goranapo** [comment]
[image: 0.jpg]
