### ISSUE TITLE
Please add BitMex exchange

### ISSUE THREAD

**Issue by housemobile** [mobnetic/BitcoinChecker#256]
Thanks

Just sent a donation!

**Comment by bendelo** [comment]
Our API documentation is here:
https://www.bitmex.com/app/apiOverview

You may be able to re-use existing code, we support the following standard APIs:

**BitcoinCharts API**
BitMEX implements the full BitcoinCharts API starting at https://www.bitmex.com/api/bitcoincharts. The BitcoinCharts API is a simple way to access trade and orderbook data in a format that is compatible with other exchanges.

**UDF API**
BitMEX also implements the UDF API popularized by TradingView. The base URL is https://www.bitmex.com/api/udf and you can view an overview here.

**Comment by bendelo** [comment]
Ahh, I just found this pull request:
https://github.com/mobnetic/BitcoinChecker/pull/239
