### ISSUE TITLE
Adding urdubit.com

### ISSUE THREAD

**Issue by danyalmanar** [mobnetic/BitcoinChecker#274]
Can someone please add urdubit. 
https://api.blinktrade.com/api/v1/PKR/ticker?crypto_currency=BTC

**Comment by drwatson84** [comment]
Urdubit should be added as well

**Comment by MaciejCiemiega** [comment]
Resolved by #275

**Comment by danyalmanar** [comment]
When will this be updated in the app itself?

Thanking You
Danyal
https://www.urdubit.com
http://pk.newsbtc.com
http://bitinfo.today
http://blockchaintech.com.pk

**Comment by MaciejCiemiega** [comment]
I will try to do it within few days.
