### ISSUE TITLE
Coinbase calls not working

### ISSUE THREAD

**Issue by QantumEntangled** [mobnetic/BitcoinChecker#287]
I woke up this morning and my Coinbase sessions aren't working. "Error: Cannot connect to server"
Tried running updates, rebooting, reinstalling, wifi, LTE, & other wifi. Still same issue. Other exchanges seem to work fine.

**Comment by QantumEntangled** [comment]
So it started working sometimes now. It seems like it works when I'm using my OpenVPN, but not on Verizon LTE, or Wifi. Except it's worked an all network connections before, also I've tried from multiple networks both public and private, I can verify that there is no network filtering on any of the private networks and there were no new IP's added to the firewalls blacklist between the time it was working and stopped working. I feel like I'm missing something here but I don't know what it is.

**Comment by zhtet036** [comment]
zhtett036@gmail.com
