### ISSUE TITLE
Remove constant/sticky notification? 

### ISSUE THREAD

**Issue by sry9681** [mobnetic/BitcoinChecker#326]
I was wondering if it's possible to remove the constant notification, I love to keep my notifications clean and it just clutter it on my screen. Maybe have an option to keep it as a background service that doesn't exit when the app is cleared from recents?

**Comment by ikt** [comment]
This is what I'm looking for, I've had to block notifications for this app, I just want the widget.

Without sounding too critical this app is amazing! Absolutely love it, just don't want the notifications.

**Comment by ikt** [comment]
Can resolve this, in the price checker options itself is 'show notification' which you can untick.

Problem solved.

**Comment by MaciejCiemiega** [comment]
As @ikt said, there was always an option to disable them.
