### ISSUE TITLE
Okcoin futeres moved to okex.com

### ISSUE THREAD

**Issue by RTEagle** [mobnetic/BitcoinChecker#338]
And old okcoin futures data dont give data. Please add new okex

**Comment by hempinternational** [comment]
Check https://www.okcoin.com/t-379.html for details

**Comment by RTEagle** [comment]
I know this data. I mean Where is okex futures in bitcoin checker? Old okcoin has parse error

**Comment by RTEagle** [comment]
Add okex futures
