### ISSUE TITLE
Default exchange

### ISSUE THREAD

**Issue by N8Thrasher** [mobnetic/BitcoinChecker#340]
Is it possible to select a default Exchange on the settings menu. It much easier to select a default one instead of doing it everytime when creating an alert.

**Comment by MaciejCiemiega** [comment]
To define an exchange as default - just long press on one on "Choose exchange" screen.

**Comment by thiswillbeyourgithub** [comment]
I think it it should be written somewhere, that function is great but really not obvious.

**Comment by zhtet036** [comment]
I'm not.

**Comment by MaciejCiemiega** [comment]
Actually it is written from the start on a default exchange, but I agree that it is not obvious. If you have any proposal of how this can be improved feel free to write it :)

**Comment by thiswillbeyourgithub** [comment]
Thanks :). Sure. I think the best way would be to add an entry in the settings called "Default exchange", all the while leaving the current long press behavior for those who understood it and so as to avoid bothering you :)
