### ISSUE TITLE
Coinbase showing different values

### ISSUE THREAD

**Issue by JacobJNilsson** [mobnetic/BitcoinChecker#384]
The coinbase site and value in app differs. Quite alot.

**Comment by elzach** [comment]
@JacobJNilsson Coinbase and GDAX will always show different rates. Coinbase is not an exchange so they offer purchases based on the spot price. [It looks like "Coinbase" is actually polling GDAX](https://github.com/mobnetic/BitcoinChecker/search?utf8=%E2%9C%93&q=gdax&type=). If anything, I think we should recommend that Coinbase is referred to as GDAX.
