### ISSUE TITLE
Add BCH

### ISSUE THREAD

**Issue by shawnshaddock** [mobnetic/BitcoinChecker#387]
Lots of exchanges are supporting Bitcoin Cash (BCH) but not available in Bitcoin checker.

**Comment by shawnshaddock** [comment]
Bitfinex is my favorite

**Comment by niukin** [comment]
Bitfinex is my favorite as well. Let's add BCH.

**Comment by MaciejCiemiega** [comment]
Added in https://github.com/mobnetic/BitcoinChecker/commit/98c33cc652d113b9d7cc53706842333ae1430048
