### ISSUE TITLE
Parsing Error BCH/IDR Bitcoin.co.id

### ISSUE THREAD

**Issue by btcid** [mobnetic/BitcoinChecker#388]
All other pairs are normal, only BCH/IDR failed with status: "Error: Parsing Error"

Do you have issue with our API? Our API endpoint is https://vip.bitcoin.co.id/api/summaries for all tickers and specifically https://vip.bitcoin.co.id/api/ticker/bchidr for BTCIDR.

Thanks

**Comment by MaciejCiemiega** [comment]
Fixed in https://github.com/mobnetic/BitcoinChecker/commit/9ca70f9aaa96f317be87e4758cdfcb45d657763a
