### ISSUE TITLE
Neo coin

### ISSUE THREAD

**Issue by jacobvw** [mobnetic/BitcoinChecker#393]
Ans has been updated to neo on bittrex and needs updating in the app

**Comment by mhuggins** [comment]
Yes please! ANS is now NEO, and ANC is now GAS.

**Comment by MaciejCiemiega** [comment]
Bittrex supports dynamic currency fetching, so please just update it in app. You can do it by clicking on blue "i" button on Checker screen and then "Synchronize".

**Comment by mhuggins** [comment]
Took a little digging, but I found it.  Thanks!
