### ISSUE TITLE
Error: Timeout error

### ISSUE THREAD

**Issue by Knoflook** [mobnetic/BitcoinChecker#395]
Got this message instead of the ticker

**Comment by Knoflook** [comment]
(miui 8.2.10.0)

**Comment by Spaghettea** [comment]
I'm also getting the timeout error. I originally thought it was just when I went from mobile network to wifi, but it does it while connected. I need to check, but it may be a battery saving program that blocks apps while the screen is off or the app is explicitly not open.

_Sent from my Samsung SAMSUNG-SM-N920A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Knoflook** [comment]
Yes, It was the battery saving app in my case. Thanks for the hint, now it is working flawlessly!

**Comment by Spaghettea** [comment]
Same here! Glad I could help!

_Sent from my Samsung SAMSUNG-SM-N920A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
