### ISSUE TITLE
Bitcoin.co.id for BCH/IDR ETH/IDR ETC/ID parsing error

### ISSUE THREAD

**Issue by Rezaxtama** [mobnetic/BitcoinChecker#399]
Please add support for bitcoin.co.id like title
https://vip.bitcoin.co.id/api/ticker/bchidr
https://vip.bitcoin.co.id/api/ticker/etcidr
https://vip.bitcoin.co.id/api/ticker/ethidr

**Comment by MaciejCiemiega** [comment]
Fixed in https://github.com/mobnetic/BitcoinChecker/commit/9ca70f9aaa96f317be87e4758cdfcb45d657763a
