### ISSUE TITLE
Bit2c not working

### ISSUE THREAD

**Issue by OrenYul** [mobnetic/BitcoinChecker#426]
Can you please check why Bit2C stopped working? 
Thanks

**Comment by MaciejCiemiega** [comment]
Works for me. Can you please check it on DataModuleTester and provide more details?

**Comment by OrenYul** [comment]
It still does not work for me. I get no data on the screen.
How do I do what you asked me to do? 
I do not know what "DataModuleTester" is.
I do not own Bit2C and I do not have anything I can test.
Please advise
