### ISSUE TITLE
Add WEX (former BTC-e)

### ISSUE THREAD

**Issue by IvoMajic** [mobnetic/BitcoinChecker#428]
www.wex.nz

**Comment by BigPeteL** [comment]
+1

**Comment by Jabroni** [comment]
I think the btce.java class just need to get updated with the new domain since it uses the same api..  (wex.nz). Tested hitting the https://wex.nz/api/3/info and it works

**Comment by zhtet036** [comment]
zhtett036

**Comment by MaciejCiemiega** [comment]
Done
