### ISSUE TITLE
Add Binance API

### ISSUE THREAD

**Issue by techieanant** [mobnetic/BitcoinChecker#433]
Binance is quickly catching up to all the big exchanges in terms of market cap. I would like to see it added to the application. They have a REST API at https://www.binance.com/restapipub.html

**Comment by spawny57** [comment]
Yes please !! It is already in the top 5 exchanges and soon to be top 3

**Comment by vincentquest** [comment]
Binance is a must ADD.

**Comment by MaciejCiemiega** [comment]
Unfortunately their API doesn't allow to read the currency pairs list that can be used in Bitcoin Checker. I have to display them as two separate currencies, but their API returns them as single pair symbol:
Examples: ETHBTC, LTCBTC, 123456, QTUMETH, BNTETH, ETHUSDT

If you would like this exchange to be added you can try contacting their support if they plan to add another API that will list all pairs in different format (either broken down to two separate fields or add a separator to the symbol)

**Comment by mrboard** [comment]
We need Binance asap... I will contact their support and let them know... But as Bittrex becomes less and less reliable, Binance is going to grow in popularity

**Comment by eyal0** [comment]
@MaciejCiemiega I, too, don't see an API that splits the currency pairs into two words.  But maybe the supported currencies could be added as a list?  Or maybe just look for every currency that ends in "BTC" and remove the "BTC" from the end?  That would probably cover most if not all currency pairs.

**Comment by MaciejCiemiega** [comment]
So, does anyone interested in this exchange wrote to them?

**Comment by fdmsaraiva** [comment]
@MaciejCiemiega just submitted a support request at Binance asking them to check this issue out and pitch in.

**Comment by MichelleLynnVIP** [comment]
Please add Binance.

**Comment by XxionxX** [comment]
I'll also contact them, thank you for the update.

**Comment by fdmsaraiva** [comment]
@MaciejCiemiega no word after over a week, but even if they do reply, considering the growth these exchanges are experiencing, it isn't likely the developers will be able to change the API any time soon. It's the single largest exchange now, so I'd say it warrants adding any necessary exceptions.

**Comment by rahilpathan** [comment]
Any expected date to add Binance?

**Comment by MaciejCiemiega** [comment]
Done in https://github.com/mobnetic/BitcoinChecker/pull/597
