### ISSUE TITLE
C-CEX exchange sync error

### ISSUE THREAD

**Issue by agitato816** [mobnetic/BitcoinChecker#437]
I'm really enjoy this app! thanks! C-CEX exchange sync doesn't work. plz fix it.

**Comment by MaciejCiemiega** [comment]
Can you provide some more details please? I've just checked it and it works properly.

**Comment by agitato816** [comment]
it doesn't sync! I cannot add this exchange C-CEX

**Comment by agitato816** [comment]
aha... I changed wifi network, it works. I don't know why... anyway thanks!

**Comment by agitato816** [comment]
it worked.
