### ISSUE TITLE
Please add Bitcoin Cash on the QuadrigaCX exchange

### ISSUE THREAD

**Issue by TravellingGuy** [mobnetic/BitcoinChecker#438]
QuadrigaCX supports buying and selling of Bitcoin Cash (BCH). Please add the BCH option for QuadrigaCX exchange.

Great widget, BTW!

**Comment by MaciejCiemiega** [comment]
Done in https://github.com/mobnetic/BitcoinChecker/commit/812abbfa5057b8cfc1b1982c780d32257db98826
