### ISSUE TITLE
BitBay - New crypto

### ISSUE THREAD

**Issue by Baks78** [mobnetic/BitcoinChecker#453]
Hello, exchange BitBay add new cryptocurrency. Can you change this on app?

**Comment by zhtet036** [comment]
zhtett036

**Comment by zhtet036** [comment]
zhtett036

**Comment by MaciejCiemiega** [comment]
Done in https://github.com/mobnetic/BitcoinChecker/commit/b40aad65f94db68d6af3d50d70c3532db28dafcd

**Comment by Baks78** [comment]
Ok. But i don't know what to do with this scripts. Please send me instructions.Pozdrawiam,Wojciech Gabrysiak03.11.2017 20:33 Maciej Ciemięga <notifications@github.com> napisał(a):Done in b40aad6

**Comment by MaciejCiemiega** [comment]
I will release it in the next update, probably within few days.
Pozdrawiam :)

**Comment by zhtet036** [comment]
zhtett036
