### ISSUE TITLE
Include Zebpay

### ISSUE THREAD

**Issue by lazygeek7** [mobnetic/BitcoinChecker#463]
Pls include Zebpay bitcoin exchange from India. A lots of bitcoin investors and cryptocurrency enthusiast in India nowadays.

**Comment by MaciejCiemiega** [comment]
Do they have only BTC/INR pair?

**Comment by lazygeek7** [comment]
Yes, unfortunately a single currency pair.
But it is India's only trusted exchange. 90% of indians have stashed their btc only via Zebpay. And the prices in India are very different from other International exchanges. For instance when BTC was $6300 on other exchanges, it was $7600 on Zebpay. So its a pain to check both the prices again and again and compare.

**Comment by MaciejCiemiega** [comment]
Ok, I've used their API as documented here: https://zebpay.zendesk.com/hc/en-us/articles/115004228609-Zebpay-APIs
but it returns different price as is posted on the website...

**Comment by MaciejCiemiega** [comment]
It looks like the API is delayed a bit, now I can see that the price on API changed and it shows the price that was on website, but on website there is a new price now so it is probably few minutes delayed relatively to website.

**Comment by MaciejCiemiega** [comment]
Added https://github.com/mobnetic/BitcoinChecker/commit/bf629de9baae1d22e5cdb123461737d3ea671cad
I will include it in next update, probably within few days.
