### ISSUE TITLE
false price at btc/usd bitfinex

### ISSUE THREAD

**Issue by virgiliuturcu** [mobnetic/BitcoinChecker#464]
Hello, the btc price on bitfinex is 7093 $ and the sofware indicates 7260 $, same after many manual  refreshes. This is happening since few days. 
Another issue is that the softwre does not speak the decimals of the omg (omise go) coin and others. It speaks only the integer part rounded +0.5, same on bitfinex. For other coins like xrp speaks all the decimals.

**Comment by Ftelf** [comment]
Me too. almost got a hearth attack. I set alarms and went outside. Birfinex, bitstamp nicely going up 7320+ and bitcoin checker alarms me going down to 7260.

**Comment by zhtet036** [comment]
zhtett036

**Comment by MaciejCiemiega** [comment]
This is price from their API (https://api.bitfinex.com/v1/pubticker/BTCUSD). If you think it is not working correctly please contact their support directly.
