### ISSUE TITLE
Bitbay.net error 

### ISSUE THREAD

**Issue by lukpe** [mobnetic/BitcoinChecker#469]
After latest update (version 1.12) the Bitbay.net check stopped working. I get "Cannot connect to server" error. I checked in another app, and everything seems to work fine.

**Comment by MaciejCiemiega** [comment]
I've only added new currency pairs (DASH an GAME) to BitBay, as shown here: https://github.com/mobnetic/BitcoinChecker/commit/b40aad65f94db68d6af3d50d70c3532db28dafcd
Nothing else was changed so it is very strange. Does it happen for any currency pair (for example BTC/USD)?

**Comment by lukpe** [comment]
It was happening for BTC / PLN, but after few hours it started working.

**Comment by MaciejCiemiega** [comment]
So most likely they have some problems with their servers. Nothing was changed in this regard inside the app.
