### ISSUE TITLE
Add Binance

### ISSUE THREAD

**Issue by jainanuj7** [mobnetic/BitcoinChecker#493]
www.binance.com
Add this exchange.
They have a couple of unique alt coins listed like Power Ledger(rose 65% today, check it out!)

**Comment by lazygeek7** [comment]
Oops, looks like binance thread was already marked as duplicate a few days back.
Sorry.
Anyways where is the original thread regarding "binance"?

**Comment by rhkarls** [comment]
https://github.com/mobnetic/BitcoinChecker/issues/433

**Comment by mrboard** [comment]
Bittrex has been the top volume exchange for most altcoins, but they are getting hacked/suspending accounts left and right. Many are moving to Binance. I love your app, but it is missing a key exchange. Please add it asap. It is a bigger and more popular exchange than many of random exchanges that you do have listed.

**Comment by MaciejCiemiega** [comment]
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
