### ISSUE TITLE
New Exchange

### ISSUE THREAD

**Issue by ldspa** [mobnetic/BitcoinChecker#537]
Can you please add paribu.com

**Comment by MysterX83** [comment]
Can you please add litebit.eu

**Comment by DonMcCoy** [comment]
Also one more important exchange coinexchange.io if possible.

Thanks

**Comment by guipucci1** [comment]
Please, can you add bitcointrade.com.br

**Comment by vankootens** [comment]
Please add binance

**Comment by jpereira** [comment]
Please, 

Add https://bitcambio.blinktrade.com/ 

ps: its the same engine as used for www.foxbit.com.br

**Comment by juancp92** [comment]
Please add Xapo
