### ISSUE TITLE
Binance

### ISSUE THREAD

**Issue by Mysteryy** [mobnetic/BitcoinChecker#565]
Would be nice to see binance added. It's the number 4 exchange by volume.

**Comment by toxicshok** [comment]
Love the Bitcoin checker app!!! Would very much like to see binance added!

**Comment by Mysteryy** [comment]
Binance has a pretty straightforward api here: https://www.binance.com/restapipub.html
All you have to do is use their endpoint: /api/v1/ticker/allPrices

This one doesn't require a signature or API key, so its as simple as one GET and you have the JSON response.

**Comment by upsidedownzebra** [comment]
Binance would be ideal. It's silly not to have it considering it's popularity.

**Comment by fseffert** [comment]
there is a pull request for binance already!

**Comment by rsix08** [comment]
This!

**Comment by MaciejCiemiega** [comment]
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
