### ISSUE TITLE
Unable to contact to server when using CoinJar

### ISSUE THREAD

**Issue by arthurcavallari** [mobnetic/BitcoinChecker#567]
I'm unable to connect to the CoinJar server to receive their updates

**Comment by mxs** [comment]
FYI this app is using the old API for CoinJar this new one can be found here: https://api.coinjar.com/v3/exchange_rates

**Comment by MaciejCiemiega** [comment]
I've fixed that. You have to sync currency pairs to make it work and re-save Checkers. I will release it in next update tomorrow. Cheers!
