### ISSUE TITLE
PLEASE add BINANCE exchange

### ISSUE THREAD

**Issue by robertbigk** [mobnetic/BitcoinChecker#605]
Wow program is best off The best . Please be do kind and add binance exchange

**Comment by xekius** [comment]
Yes please add binance, this app is one of the best I ever came across.

**Comment by andreivoinea93** [comment]
+1

**Comment by chaitanyapotti** [comment]
+1

**Comment by Xyic0re** [comment]
+1

**Comment by Mj11048** [comment]
Pretty please add github

**Comment by xdslx** [comment]
Isnt there anyone to add BINANCE for the Bitcoin Checker

**Comment by nelson777** [comment]
+1

**Comment by RichyHBM** [comment]
Hopefully I may have some spare time soon to add it!

**Comment by rastoha** [comment]
+1 Many thanks. Now that Bittrex temporarily doesnt approves new members, Binance is becoming the major altcoin exchange.

**Comment by MaciejCiemiega** [comment]
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
