### ISSUE TITLE
Additional Exchange 

### ISSUE THREAD

**Issue by hercmaroudas** [mobnetic/BitcoinChecker#607]
Please add Kucoin and Binance exchanges?

**Comment by RichyHBM** [comment]
I can hopefully look into adding these soon!

**Comment by hercmaroudas** [comment]
Thank you.

**Comment by RichyHBM** [comment]
Kucoin is in PR, and someone has also added binance in a pr

**Comment by jwurton** [comment]
Www.Coinexchange.io
