### ISSUE TITLE
Binance 

### ISSUE THREAD

**Issue by jayesh1306** [mobnetic/BitcoinChecker#611]
Add binance cryptocurrency exchange

**Comment by the3dmen** [comment]
I agree

**Comment by XxionxX** [comment]
I would also like this exchange please. Do we need to donate?

**Comment by Silverspark75** [comment]
hoping binance will help

**Comment by lethalbrains** [comment]
Binance is a major exchange. Must be added.

**Comment by PaulioArmani** [comment]
I agree, please add binance

**Comment by RJC73** [comment]
I agree. Please add Binance. Have given your app 5-stars.

**Comment by ktopcuoglu** [comment]
Binance required.

**Comment by rahilpathan** [comment]
I agree, Binance necessary

**Comment by MaciejCiemiega** [comment]
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
