### ISSUE TITLE
Can you include Binance.com exchange prices

### ISSUE THREAD

**Issue by nick-g4golf** [mobnetic/BitcoinChecker#623]

**Comment by cad0p** [comment]
Me too!

**Comment by carlos-ballester** [comment]
Yes please, add binance exchange (which by the way is the biggest exchange right now in terms of volume)

**Comment by begrossi** [comment]
+1 to Binance

**Comment by unklejo** [comment]
+1 Binance please.

**Comment by jasonnm** [comment]
Yes please!

**Comment by jammyto10** [comment]
How do I add binnacle.com please

**Comment by Guruleenyc** [comment]
Plus one. This would be great since it's the leading exchange. Thank you in advance.

**Comment by MaciejCiemiega** [comment]
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
