### ISSUE TITLE
Add new coins and exchanges

### ISSUE THREAD

**Issue by solarscream** [mobnetic/BitcoinChecker#627]
Add Binance, YoBit exchanges.
Add Tronix (TRX), Stellar Lumen (STR/XLM), SoonCoin (SOON) coins.

**Comment by begrossi** [comment]
+1 to Binance.
YoBit was added before..

**Comment by alnetosilva** [comment]
+1 Binance (TRX), PoE, XVG

**Comment by shaunedwardsus** [comment]
+1 Binance

**Comment by exchrg** [comment]
+1 Binance
Please!

**Comment by MaciejCiemiega** [comment]
Please create single issue per single exchange.
