### ISSUE TITLE
Please add Binance Exchange

### ISSUE THREAD

**Issue by sriramsujit** [mobnetic/BitcoinChecker#635]
Hi team,
Please add Binance Exchange to your list.

**Comment by MaciejCiemiega** [comment]
Dupicate of https://github.com/mobnetic/BitcoinChecker/issues/433

**Comment by zhtet036** [comment]
zhtett036@gmail.com9

**Comment by zhtet036** [comment]
zhtett036@gmail.com

**Comment by zhtet036** [comment]
zhtett036@gmail.com
